go1:
  model_name: policy_1.pt #"policy_24_07_.pt" #"policy_14_07_6950.pt" #"policy_14_07_4450.pt" # "policy_10000_new.pt" # "policy_6400_new_walk_11_07.pt" # "10_23_43.pt" #"policy_new_param.pt" #"policy_new_walk.pt" #"policy_test.pt" #"Mar25_16-22-14_500.pt"
  observations: ["ang_vel" ,"gravity_vec","command","dof_pos","dof_vel","action","sin","cos"] #Full_OBS if need another check your obs in legged_gym
  #["lin_vel" ,"ang_vel" ,"gravity_vec" ,"command","dof_pos","dof_vel","action"]
  clip_obs: 100.0
  clip_actions: 100.0
  lin_vel_scale: 2.0
  action_scale: 0.25
  ang_vel_scale: 0.25
  dof_pos_scale: 1.0
  dof_vel_scale: 0.05
  decimation: 4
  cycle_time: 0.4
  torque_limits: [33.5, 33.5, 33.5,
                  33.5, 33.5, 33.5,
                  33.5, 33.5, 33.5,
                  33.5, 33.5, 33.5]
#   rl_kp: [20, 20, 20,
#         20, 20, 20,
#         20, 20, 20,
#         20, 20, 20]                  
  rl_kp: [25, 25, 25,
          25, 25, 25,
          25, 25, 25,
          25, 25, 25]
  rl_kd: [1.5, 1.5, 1.5,
          1.5, 1.5, 1.5,
          1.5, 1.5, 1.5,
          1.5, 1.5, 1.5]
  fixed_kp: [40, 40, 40,
             40, 40, 40,
             40, 40, 40, 
             40, 40, 40]
  fixed_kd: [1, 1, 1,
             1, 1, 1,
             1, 1, 1,
             1, 1, 1]
  commands_scale: [2.0, 2.0, 0.25]
  default_dof_pos: [ 0.0, 0.8, -1.5, # FL
                    -0.0, 0.8, -1.5, # FR
                     0.0, 1.1, -1.7, # RL
                    -0.0, 1.1, -1.7] # RR
                   # [ 0.0, 0.8, -1.5, # FL
                   # -0.0, 0.8, -1.5, # FR
                   #  0.0, 1.1, -1.7, # RL
                   # -0.0, 1.1, -1.7] # RR
  joint_names: ["FL_hip", "FL_thigh", "FL_calf",
                "FR_hip", "FR_thigh", "FR_calf",
                "RL_hip", "RL_thigh", "RL_calf",
                "RR_hip", "RR_thigh", "RR_calf"]

