go1:
  model_name: "Mar14_13-45-05_model_400.pt"
  clip_obs: 100.0
  clip_actions: 100.0
  action_scale: 0.25
  ang_vel_scale: 0.25
  dof_pos_scale: 1.0
  dof_vel_scale: 0.05
  default_dof_pos: [ 0.0, 0.8, -1.3, # FL
                    -0.0, 0.8, -1.3, # FR
                     0.0, 0.8, -1.3, # RL
                    -0.0, 0.8, -1.3] # RR
  joint_names: ["FL_hip", "FL_thigh", "FL_calf",
                "FR_hip", "FR_thigh", "FR_calf",
                "RL_hip", "RL_thigh", "RL_calf",
                "RR_hip", "RR_thigh", "RR_calf"]

