#include "system_state.hpp"
namespace sim2real {
const char* SystemStateName(SystemState s){switch(s){
#define NAME(x) case SystemState::x:return #x
 NAME(INIT);NAME(STANDBY);NAME(TAKEOVER);NAME(ACTIVE);NAME(CONTROLLED_STOP);NAME(SYSTEM_HOLD);NAME(EMERGENCY_FAULT);
#undef NAME
 }return "UNKNOWN";}
const char* SystemPhaseName(SystemPhase s){switch(s){
#define NAME(x) case SystemPhase::x:return #x
 NAME(STOCK);NAME(DISARMED);NAME(TAKEOVER_REQUESTED);NAME(PRECHECK);NAME(SPORT_RELEASE_REQUIRED);
 NAME(SPORT_RELEASE_VERIFIED);NAME(LOW_LEVEL_ARMED);NAME(HOLD_CURRENT);NAME(STAND_TRANSITION);NAME(HOLDING);
 NAME(RL_ZERO);NAME(RL_ACTIVE);NAME(CONTROLLED_ABORT);NAME(LIE_DOWN_TRANSITION);NAME(OUTPUT_STOPPING);NAME(RETURN_TO_STOCK);
 NAME(FAULT_LATCHED);NAME(EMERGENCY_DAMP);NAME(ARM_RETURN_HOME);NAME(ARM_HOME_BLOCKED);NAME(ARM_HOME_SETTLE);
 NAME(PD_CAPTURE);NAME(LIE_DOWN);NAME(LIE_DOWN_VERIFY);NAME(LIE_DOWN_BLOCKED);NAME(LIE_DOWN_HOLD);
#undef NAME
 }return "UNKNOWN";}
} // namespace sim2real
