robot: "go2_rars01"
robot_scene: "scene_stage4d.xml"
base_body: "base"
domain_id: 1
interface: "lo"
enable_unitree_bridge: 0
enable_ros_bridge: 1
use_joystick: 0
joystick_type: "xbox"
joystick_device: "/dev/input/js0"
joystick_bits: 16
print_scene_information: 1
enable_elastic_band: 0
odom_topic: "/sim/ground_truth_odom"
world_frame: "camera_init"
lidar_rate: 10.0
lidar_horizontal_samples: 360
lidar_vertical_lines: 18
lidar_min_range: 0.5
lidar_max_range: 100.0
